version: '1.0'

services:
  deepglm:
    container_name: DeepGLM
    image: ghcr.io/idarkboss/deepclaude:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "26150:8000"
    volumes:
      - ./app/model_manager/model_configs.json:/app/app/model_manager/model_configs.json
    restart: always # 建议添加 restart policy，确保容器意外退出后可以自动重启
